const card_mean = {
    // 格式: [正位关键词, 逆位关键词]
    meanings: [  // 英文版本（保持你提供的原文，仅轻微格式整理）
        ["innocence, new beginnings, free spirit", "recklessness, taken advantage of, inconsideration"],
        ["willpower, desire, creation, manifestation", "trickery, illusions, out of touch"],
        ["intuitive, unconscious, inner voice", "lack of center, lost inner voice, repressed feelings"],
        ["motherhood, fertility, nature", "dependence, smothering, emptiness, nosiness"],
        ["authority, structure, control, fatherhood", "tyranny, rigidity, coldness"],
        ["tradition, conformity, morality, ethics", "rebellion, subversiveness, new approaches"],
        ["partnerships, duality, union", "loss of balance, one-sidedness, disharmony"],
        ["direction, control, willpower", "lack of control, lack of direction, aggression"],
        ["inner strength, bravery, compassion, focus", "self doubt, weakness, insecurity"],
        ["contemplation, search for truth, inner guidance", "loneliness, isolation, lost your way"],
        ["change, cycles, inevitable fate", "no control, clinging to control, bad luck"],
        ["cause and effect, clarity, truth", "dishonesty, unaccountability, unfairness"],
        ["sacrifice, release, martyrdom", "stalling, needless sacrifice, fear of sacrifice"],
        ["end of cycle, beginnings, change, metamorphosis", "fear of change, holding on, stagnation, decay"],
        ["middle path, patience, finding meaning", "extremes, excess, lack of balance"],
        ["addiction, materialism, playfulness", "freedom, release, restoring control"],
        ["sudden upheaval, broken pride, disaster", "disaster avoided, delayed disaster, fear of suffering"],
        ["hope, faith, rejuvenation", "faithlessness, discouragement, insecurity"],
        ["unconscious, illusions, intuition", "confusion, fear, misinterpretation"],
        ["joy, success, celebration, positivity", "negativity, depression, sadness"],
        ["reflection, reckoning, awakening", "lack of self awareness, doubt, self loathing"],
        ["fulfillment, harmony, completion", "incompletion, no closure"],

        // 权杖组 (Wands)
        ["action, adventure, fearlessness", "anger, impulsiveness, recklessness"],
        ["big picture, leader, overcoming challenges", "impulsive, overbearing, unachievable expectations"],
        ["courage, determination, joy", "selfishness, jealousy, insecurities"],
        ["exploration, excitement, freedom", "lack of direction, procrastination, creating conflict"],
        ["planning, making decisions, leaving home", "fear of change, playing safe, bad planning"],
        ["looking ahead, expansion, rapid growth", "obstacles, delays, frustration"],
        ["competition, rivalry, conflict", "avoiding conflict, respecting differences"],
        ["victory, success, public reward", "excess pride, lack of recognition, punishment"],
        ["rapid action, movement, quick decisions", "panic, waiting, slowdown"],
        ["resilience, grit, last stand", "exhaustion, fatigue, questioning motivations"],
        ["accomplishment, responsibility, burden", "inability to delegate, overstressed, burnt out"],
        ["creation, willpower, inspiration, desire", "lack of energy, lack of passion, boredom"],
        ["community, home, celebration", "lack of support, transience, home conflicts"],
        ["perseverance, defensive, maintaining control", "give up, destroyed confidence, overwhelmed"],

        // 圣杯组 (Cups)
        ["new feelings, spirituality, intuition", "emotional loss, blocked creativity, emptiness"],
        ["unity, partnership, connection", "imbalance, broken communication, tension"],
        ["friendship, community, happiness", "overindulgence, gossip, isolation"],
        ["apathy, contemplation, disconnectedness", "sudden awareness, choosing happiness, acceptance"],
        ["loss, grief, self-pity", "acceptance, moving on, finding peace"],
        ["familiarity, happy memories, healing", "moving forward, leaving home, independence"],
        ["searching for purpose, choices, daydreaming", "lack of purpose, diversion, confusion"],
        ["walking away, disillusionment, leaving behind", "avoidance, fear of change, fear of loss"],
        ["satisfaction, emotional stability, luxury", "lack of inner joy, smugness, dissatisfaction"],
        ["inner happiness, fulfillment, dreams coming true", "shattered dreams, broken family, domestic disharmony"],
        ["happy surprise, dreamer, sensitivity", "emotional immaturity, insecurity, disappointment"],
        ["following the heart, idealist, romantic", "moodiness, disappointment"],
        ["compassion, calm, comfort", "martyrdom, insecurity, dependence"],
        ["compassion, control, balance", "coldness, moodiness, bad advice"],

        // 宝剑组 (Swords)
        ["breakthrough, clarity, sharp mind", "confusion, brutality, chaos"],
        ["difficult choices, indecision, stalemate", "lesser of two evils, no right choice, confusion"],
        ["heartbreak, suffering, grief", "recovery, forgiveness, moving on"],
        ["rest, restoration, contemplation", "restlessness, burnout, stress"],
        ["unbridled ambition, win at all costs, sneakiness", "lingering resentment, desire to reconcile, forgiveness"],
        ["transition, leaving behind, moving on", "emotional baggage, unresolved issues, resisting transition"],
        ["deception, trickery, tactics and strategy", "coming clean, rethinking approach, deception"],
        ["imprisonment, entrapment, self-victimization", "self acceptance, new perspective, freedom"],
        ["anxiety, hopelessness, trauma", "hope, reaching out, despair"],
        ["failure, collapse, defeat", "can't get worse, only upwards, inevitable end"],
        ["curiosity, restlessness, mental energy", "deception, manipulation, all talk"],
        ["complexity, perceptiveness, clear mindedness", "cold hearted, cruel, bitterness"],
        ["action, impulsiveness, defending beliefs", "no direction, disregard for consequences, unpredictability"],
        ["head over heart, discipline, truth", "manipulative, cruel, weakness"],

        // 星币组 (Pentacles)
        ["opportunity, prosperity, new venture", "lost opportunity, missed chance, bad investment"],
        ["balancing decisions, priorities, adapting to change", "loss of balance, disorganized, overwhelmed"],
        ["teamwork, collaboration, building", "lack of teamwork, disorganized, group conflict"],
        ["conservation, frugality, security", "greediness, stinginess, possessiveness"],
        ["need, poverty, insecurity", "recovery, charity, improvement"],
        ["charity, generosity, sharing", "strings attached, stinginess, power and domination"],
        ["hard work, perseverance, diligence", "work without results, distractions, lack of rewards"],
        ["apprenticeship, passion, high standards", "lack of passion, uninspired, no motivation"],
        ["fruits of labor, rewards, luxury", "reckless spending, living beyond means, false success"],
        ["legacy, culmination, inheritance", "fleeting success, lack of stability, lack of resources"],
        ["ambition, desire, diligence", "lack of commitment, greediness, laziness"],
        ["efficiency, hard work, responsibility", "laziness, obsessiveness, work without reward"],
        ["practicality, creature comforts, financial security", "self-centeredness, jealousy, smothering"],
        ["abundance, prosperity, security", "greed, indulgence, sensuality"]
    ],

    meanings_ZH: [  // 中文直译版本（严格基于英文原文翻译）
        ["纯真、新的开始、自由精神", "鲁莽、被利用、考虑不周"],
        ["意志力、欲望、创造、显化", "欺骗、幻觉、脱离现实"],
        ["直觉、潜意识、内心的声音", "失去中心、迷失内心的声音、压抑的情感"],
        ["母性、生育能力、自然", "依赖、窒息、空虚、爱管闲事"],
        ["权威、结构、控制、父性", "暴政、僵化、冷酷"],
        ["传统、顺从、道德、伦理", "叛逆、颠覆性、新方法"],
        ["伙伴关系、二元性、结合", "失去平衡、片面、不和谐"],
        ["方向、控制、意志力", "失去控制、方向不明、侵略性"],
        ["内在力量、勇敢、同情、专注", "自我怀疑、软弱、不安全感"],
        ["沉思、寻求真理、内在指引", "孤独、孤立、迷失方向"],
        ["变化、周期、不可避免的命运", "无法掌控、紧抓控制、坏运气"],
        ["因果、清晰、真相", "不诚实、不负责任、不公平"],
        ["牺牲、释放、殉道", "拖延、无谓的牺牲、害怕牺牲"],
        ["周期结束、新的开始、变化、蜕变", "害怕改变、执着不放、停滞、衰败"],
        ["中道、耐心、寻找意义", "极端、过度、缺乏平衡"],
        ["成瘾、物质主义、玩乐", "自由、释放、恢复控制"],
        ["突然剧变、破碎的骄傲、灾难", "灾难避免、延迟的灾难、害怕受苦"],
        ["希望、信念、恢复活力", "缺乏信念、沮丧、不安全感"],
        ["潜意识、幻觉、直觉", "困惑、恐惧、误解"],
        ["喜悦、成功、庆祝、积极", "消极、抑郁、悲伤"],
        ["反思、清算、觉醒", "缺乏自我觉知、怀疑、自我厌恶"],
        ["圆满、和谐、完成", "未完成、没有、关闭"],

        // 权杖组
        ["行动、冒险、无畏", "愤怒、冲动、鲁莽"],
        ["大局观、领导者、克服挑战", "冲动、专横、无法实现的目标"],
        ["勇气、决心、喜悦", "自私、嫉妒、不安全感"],
        ["探索、兴奋、自由", "方向不明、拖延、制造冲突"],
        ["规划、做决定、离开家园", "害怕改变、求稳、糟糕的规划"],
        ["展望未来、扩张、快速成长", "障碍、延迟、挫折"],
        ["竞争、对抗、冲突", "避免冲突、尊重差异"],
        ["胜利、成功、公开奖励", "过度骄傲、缺乏认可、惩罚"],
        ["快速行动、移动、快速决定", "恐慌、等待、减速"],
        ["韧性、毅力、最后一搏", "疲惫、疲劳、质疑动机"],
        ["成就、责任、重担", "无法授权、压力过大、 烧毁"],
        ["创造、意志力、灵感、欲望", "缺乏能量、缺乏热情、无聊"],
        ["社区、家庭、庆祝", "缺乏支持、短暂、家庭冲突"],
        ["坚持、防御、维持控制", "放弃、信心崩塌、被压倒"],

        // 圣杯组
        ["新的情感、灵性、直觉", "情感损失、创意被阻、空虚"],
        ["团结、伙伴关系、连接", "失衡、沟通破裂、紧张"],
        ["友谊、社区、幸福", "过度放纵、八卦、孤立"],
        ["冷漠、沉思、疏离", "突然觉醒、选择快乐、接受"],
        ["损失、悲伤、自怜", "接受、继续前进、找到平静"],
        ["熟悉、快乐回忆、疗愈", "向前迈进、离开家园、独立"],
        ["寻找目的、选择、白日梦", "缺乏目的、转移注意力、困惑"],
        ["走开、幻灭、放下过去", "回避、害怕改变、害怕损失"],
        ["满足、情感稳定、奢侈", "缺乏内在喜悦、自满、不满"],
        ["内在幸福、圆满、梦想成真", "梦想破碎、家庭破裂、家庭不和谐"],
        ["快乐的惊喜、梦想家、敏感", "情感不成熟、不安全感、失望"],
        ["受心指引、理想主义、浪漫", "情绪化、失望"],
        ["同情、平静、安慰", "殉道、不安全感、依赖"],
        ["同情、控制、平衡", "冷酷、情绪化、坏建议"],

        // 宝剑组
        ["突破、清晰、敏锐的头脑", "混乱、残酷、混乱"],
        ["艰难的选择、犹豫不决、僵局", "两害相权取其轻、没有正确的选择、困惑"],
        ["心碎、痛苦、悲伤", "恢复、原谅、继续前进"],
        ["休息、恢复、沉思", "不安、燃尽、压力"],
        ["无拘束的野心、不惜一切代价取胜、偷偷摸摸", " 持续怨恨、渴望和解、原谅"],
        ["过渡、放下、继续前进", "情感包袱、未解决的问题、抵抗过渡"],
        ["欺骗、诡计、策略与战术", "坦白、重新思考方法、欺骗"],
        ["监禁、困住、自我受害", "自我接受、新视角、自由"],
        ["焦虑、绝望、创伤", "希望、伸手求助、绝望"],
        ["失败、崩溃、败北", "不会更糟、只有向上、不可避免的结束"],
        ["好奇、不安、精神能量", "欺骗、操纵、空谈"],
        ["复杂、洞察力、头脑清晰", "冷酷无情、残忍、苦涩"],
        ["行动、冲动、捍卫信念", "没有方向、无视后果、不可预测"],
        ["理智优先、纪律、真相", "操纵、残酷、软弱"],

        // 星币组
        ["机会、繁荣、新事业", "错失机会、错过、坏投资"],
        ["平衡决策、优先级、适应变化", "失去平衡、混乱、不知所措"],
        ["团队合作、协作、建设", "缺乏团队合作、混乱、团体冲突"],
        ["保存、节俭、安全", "贪婪、吝啬、占有欲"],
        ["需求、贫穷、不安全感", "恢复、慈善、改善"],
        ["慈善、慷慨、分享", "附加条件、吝啬、权力支配"],
        ["努力工作、坚持、勤奋", "没有结果的工作、分心、缺乏回报"],
        ["学徒、热情、高标准", "缺乏热情、没有灵感、没有动力"],
        ["劳动成果、奖励、奢侈", "挥霍、超支、虚假成功"],
        ["遗产、巅峰、继承", "短暂成功、缺乏稳定、缺乏资源"],
        ["野心、欲望、勤奋", "缺乏承诺、贪婪、懒惰"],
        ["效率、努力工作、责任", "懒惰、强迫症、没有回报的工作"],
        ["务实、物质享受、财务安全", "自我中心、嫉妒、窒息"],
        ["丰盛、繁荣、安全", "贪婪、放纵、感官享受"]
    ]
};

export { card_mean };